name: cytodatagen
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - ipykernel
  # setuptools that support version inference from source code management system
  - setuptools-scm
  # scanpy compatible fc analysis package, but felt still a bit clunky
  - anndata
  - pip:
    - pyhere
    - flowkit
